baseURL: https://cryptohack.net
relativeURLs: true
canonifyURLs: true
uglyURLs: true
languageCode: en-us
title: Cryptohack
theme: hugo-zen

params:
  logo: /images/cryptofist.png
  twitter: https://twitter.com/cryptohacknet
  meetup: https://www.meetup.com/cryptohack-melbourne/events/227170695/
  slack: https://cryptohack.herokuapp.com
