baseURL: https://hackforprivacy.org
relativeURLs: true
canonifyURLs: true
uglyURLs: true
languageCode: en-us
title: Hack for Privacy
theme: hugo-zen

params:
  logo: /images/cryptofist.png
  twitter: https://twitter.com/hackforprivacy
  facebook: https://www.facebook.com/hackforprivacy/
  meetup: https://www.meetup.com/hack-for-privacy/
  slackjoin: https://cryptohack.herokuapp.com
  slack: https://hackforprivacy.slack.com
  rss: https://hackforprivacy.org/index.xml
