relativeURLs: true
canonifyURLs: true
languageCode: en-us
title: cryptohack
canonifyurls: true

params:
  logo: /images/cryptofist.png
  twitter: https://twitter.com/cryptohacknet
  meetup: https://www.meetup.com/cryptohack-melbourne/events/227170695/
  slack: https://cryptohack.herokuapp.com
