baseURL: https://cryptohack.net
relativeURLs: true
canonifyURLs: true
uglyURLs: true
languageCode: en-us
title: Cryptohack
theme: hugo-zen

params:
  logo: /images/cryptofist.png
  twitter: https://twitter.com/cryptohacknet
  facebook: https://www.facebook.com/cryptohacknet
  meetup: https://www.meetup.com/cryptohack-melbourne/
  slackjoin: https://cryptohack.herokuapp.com
  slack: https://cryptohack.slack.com
  rss: https://cryptohack.net/index.xml
